name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.12']
        include:
          - os: windows-latest
            asset_name: HotwheelsPDF-Windows.exe
            asset_content_type: application/vnd.microsoft.portable-executable
          - os: macos-latest
            asset_name: HotwheelsPDF-Mac.dmg
            asset_content_type: application/x-apple-diskimage

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller pillow

    - name: Build Windows Executable
      if: matrix.os == 'windows-latest'
      run: |
        python build_executable.py

    - name: Build macOS App
      if: matrix.os == 'macos-latest'
      run: |
        python build_executable.py
        # Create a temporary directory for DMG creation
        mkdir -p dist/dmg
        mv "dist/HotwheelsPDF" "dist/dmg/HotwheelsPDF.app"
        # Create DMG file
        hdiutil create -volname "HotwheelsPDF" -srcfolder "dist/dmg" -ov -format UDZO "dist/HotwheelsPDF-Mac.dmg"

    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/HotwheelsPDF.exe
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: ${{ matrix.asset_content_type }}

    - name: Upload Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/HotwheelsPDF-Mac.dmg
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: ${{ matrix.asset_content_type }}
