name: Build Executables

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build executable
      run: python build_executable.py
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: HotwheelsPDF-Windows
        path: dist/HotwheelsPDF.exe
        retention-days: 90
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build executable
      run: python build_executable.py
    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "HotwheelsPDF" -srcfolder HotwheelsPDF.app -ov -format UDZO HotwheelsPDF.dmg
    - name: Upload Mac Build
      uses: actions/upload-artifact@v4
      with:
        name: HotwheelsPDF-Mac
        path: dist/HotwheelsPDF.dmg
        retention-days: 90
        if-no-files-found: error
